swagger: "2.0"
info:
  title: api-auth-autopark
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /schedule:
    post:
      summary: Greet a user
      operationId: autopark-function
      x-google-backend:
        address: "https://{{ variable1 }}-{{ variable2 }}.cloudfunctions.net/dev2-schedule"
        deadline: 60.0
