name: GitHub_Subnet_TEST

on:
  workflow_dispatch:
    inputs:
      SUBNET_IDs_LAMBDA:
        description: SUBNET IDs for Lambda
        type: string
        required: true

      SUBNET_IDs_RDS:
        description: SUBNET IDs for RDS
        type: string
        required: true
      
env:
  SUBNET_ID_LAMBDA: ${{ inputs.SUBNET_IDs_LAMBDA }}
  SUBNET_ID_RDS: ${{ inputs.SUBNET_IDs_RDS }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Parse subnet IDs
        id: parse_subnets
        run: |
          echo "::set-output name=subnets_lambda::[\\\"$(echo ${{ env.SUBNET_ID_LAMBDA }} | sed 's/,/\\", \\"/g')\\\"]"
          echo "::set-output name=subnets_rds::[\\\"$(echo ${{ env.SUBNET_ID_RDS }} | sed 's/,/\\", \\"/g')\\\"]"

      - name: Printing the parsed value for Lambda
        id: parsed-printing-lambda
        run: |
          echo PARSED-SUBNETS=${{ steps.parse_subnets.outputs.subnets_lambda }}

      - name: Printing the parsed value for RDS
        id: parsed-printing-rds
        run: |
          echo PARSED-SUBNETS=${{ steps.parse_subnets.outputs.subnets_rds }}

      # - name: Configure AWS Credentials for DEV ENV
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: "ap-south-1"

      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Install Terraform
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     terraform_version: 1.1.0
      
      # - name: Initialize Terraform
      #   run: terraform init

      # - name: Plan Terraform
      #   run: terraform plan -var-file="dev.tfvars" -var="db_subnet_ids=${{ steps.parse_subnets.outputs.subnets }}"



        # -var="db_subnet_ids=[\"subnet-07d0a19dba27e6703\", \"subnet-001e69de25e3fd631\"] for github action ui
        # "SUBNET_IDs": "[\\\"subnet-07d0a19dba27e6703\\\", \\\"subnet-001e69de25e3fd631\\\"]" for github api




        # subnet-07d0a19dba27e6703,subnet-07d0a19dba27e6704,subnet-07d0a19dba27e6705