name: GitHub_Subnet_TEST

on:
  workflow_dispatch:
    inputs:
      SUBNET_IDs:
        description: SUBNET IDs
        type: string
        required: true

env:
  SUBNET_ID_DEV: ${{ inputs.SUBNET_IDs }}

jobs:
  Printing_Subnet_ID:
    runs-on: ubuntu-latest
    steps:
      - name: Set subnet_ids variable
        run: |
          echo "Subnet IDs: [${{ inputs.SUBNET_IDs }}]"
        shell: bash

  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials for DEV ENV
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-south-1"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0
      
      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan -var-file="dev.tfvars" -var="db_subnet_ids=[${{env.SUBNET_ID_DEV}}]"

