name: TESTING_PIPELINE

on:
  workflow_dispatch:
    inputs:

      REGION: 
        description: Region name 
        type: string
        required: true

      ACCESS_KEY_ID:
        description: Acces key ID
        type: string
        required: true
      
      SECRET_ACCESS_KEY_ID:
        description: Secret Acces key ID
        type: string
        required: true
env:

  REGION: ${{inputs.REGION}}
  AWS_ACCESS_KEY_INPUT: ${{inputs.ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY_INPUT: ${{inputs.SECRET_ACCESS_KEY_ID}}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_INPUT }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY_INPUT }}
          aws-region: ${{env.REGION}}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.0

        
      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: | 
          terraform plan -var-file="dev.tfvars" \
          -var="region=${{env.REGION}}"


