
name : Destroy_WF_DEV3
on:
  workflow_dispatch:
    inputs:
      REGION_DEV:
        description: Region name
        type: string
        required: true
      
      AWS_ACCOUNT_NO_DEV:
        description: Account Number
        type: number
        required: true

jobs:
# Printing input Values.
    Checking-for-input-Values1:
        runs-on: ubuntu-latest
        
        steps:
        - name: Print input Values for DEV2
          if: github.ref == 'refs/heads/DEV2'
          run: |
            echo "Region- ${{inputs.REGION_DEV}}"
            echo "AWS Account NO- ${{inputs.AWS_ACCOUNT_NO_DEV}}"

        - name: Print input Values for DEV3
          if: github.ref == 'refs/heads/DEV3'
          run: |
              echo "Region- ${{inputs.REGION_DEV}}"
              echo "AWS Account NO- ${{inputs.AWS_ACCOUNT_NO_DEV}}"
