
name : Destroy_GitHub_API_TEST
on:
  workflow_dispatch:
    inputs:
      REGION:
        description: Region name
        type: string
        required: true


env:
    REGION_DEV: ${{inputs.REGION}}
    REGION_PROD: ${{inputs.REGION}}
jobs:
# Printing input Values.
    Checking-for-input-Values1:
        runs-on: ubuntu-latest
        
        steps:
        - name: Print input Values for DEV
          if: github.ref == 'refs/heads/DEV2'
          run: |
            echo "Region- ${{env.REGION_DEV}}"
            

        - name: Print input Values for Prod
          if: github.ref == 'refs/heads/DEV3'
          run: |
              echo "Region- ${{env.REGION_PROD}}"
              
