
name: GitHub_Subnet_TEST

on:
  workflow_dispatch:
    inputs:
      SUBNET_IDs:
        description: SUBNET IDs
        type: string
        required: true

env:
  SUBNET_ID_DEV: ${{ inputs.SUBNET_IDs }}

jobs:
  Printing_Subnet_ID:
    runs-on: ubuntu-latest
    steps:
      - name: Set subnet_ids variable
        run: |
          echo "Subnet IDs: [${{env.SUBNET_ID_DEV}}]"
          shell: /usr/bin/bash
