name: GitHub API Test Workflow
on:
    workflow_dispatch:
        inputs:
            name:
                description: "Name"
                required: true
                type: string
            company:
                description: "Name of the company"
                required: true
                type: string

env:
    TEST_VAR_GITHUB_API: val-wf



jobs:
    job1:
        name: Check for env update
        runs-on: ubuntu-latest
        environment: DEV
        steps:
            - name: Print ENVs
              run: |
                echo "${{vars.TEST_VAR_GITHUB_API}}"
                echo "$TEST_VAR_GITHUB_API"
                echo "Hello, my name is ${{inputs.name}} and my company is ${{inputs.company}}"
