
name : GitHub_Subnet_TEST
on:
  workflow_dispatch:
    

env:
  SUBNET_ID_DEV: subnet-07d0a19dba27e6703, subnet-001e69de25e3fd631, subnet-07d0a19dba27e6703, subnet-001e69de25e3fd631
jobs:

    Printing_Subnet_ID:
        runs-on: ubuntu-latest
        steps:
          - name: Printing Subnet IDs
            run: |
              echo "${{env.SUBNET_ID_DEV}}"
            
            
