name: Workflow A
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Produce artifact
        id: artifact_step
        run: |
          echo "Hello, world" > hello.txt
      - name: Archive the artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: hello.txt
      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'

