name: Workflow B
on:
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow A
        uses: actions/checkout@v2
      - name: Get artifact name from Workflow A
        id: get_artifact_name
        run: echo "::set-output name=artifact_name::${{ needs.Workflow_A.outputs.artifact_name }}"
      - name: Download artifact
        # Download the artifact from Workflow A using the specified name
        uses: actions/download-artifact@v2
        with:
          name: ${{ steps.get_artifact_name.outputs.artifact_name }}
          path: ./downloaded
      - name: Use the artifact
        run: cat ./downloaded/hello.txt
