name: Workflow A
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Produce artifact
        id: artifact_step
        run: |
          echo "Hello, world" > hello.txt
      - name: Archive the artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact # Provide a default name for the artifact
          path: hello.txt
