
name : wf2 download
on:
  workflow_dispatch:
    # inputs:
    #   REGION_DEV:
    #     description: Region name for DEV ENV
    #     type: string
    #     required: true

# env:
  # REGION_DEV: ${{inputs.REGION_DEV}}
jobs:
# Configuring AWS.
    # AWS-configure:
    #     runs-on: ubuntu-latest
  
    #     steps:
    #       - name: Configure AWS Credentials(DEV ENV)
    #         uses: aws-actions/configure-aws-credentials@v4
    #         with:
    #           aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY }}
    #           aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #           aws-region: ${{ env.REGION_DEV }}
  get_workflow_run_number:
    runs-on: ubuntu-latest
    outputs:
      workflow_run_number: ${{ steps.get_run.outputs.workflow_run_number }}
    steps:
      - name: Get latest workflow run number of Workflow 1
        id: get_run
        run: |
          echo "::set-output name=workflow_run_number::$(curl -s -X GET -H 'Accept: application/vnd.github.v3+json' -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/workflows/workflow1.yaml/runs | jq -r '.workflow_runs[0].id')"
  download_artifact:
    runs-on: ubuntu-latest
    needs: get_workflow_run_number
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-name
          workflow_run: ${{ needs.get_workflow_run_number.outputs.workflow_run_number }}
