name: "Building and Pushing Docker Image"

on:
  workflow_dispatch:  
    secrets:
      REGISTRY_USERNAME:
        description: "Username of Docker"
        required: true
      REGISTRY_PASSWORD: 
        description: "Password for Docker"
        required: true


jobs:
  job1:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}

      - name: Build and push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.REGISTRY_USERNAME}}/test1:1.0

  job2:
    name: Print name
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello my name is Ronak"