# Variables and secrets in the repo:
    # Variables:-
    # TEST_REGION: ap-south-1
    # TEST_AWS_ACCOUNT_NO: "889148926241"
    # TEST_STATEMENT_ID: custom-resource-policy
    # TEST_LAMBDA_START: autopark-start-vm-dev
    # TEST_LAMBDA_STOP: autopark-stop-vm-dev

    # TEST_TF_STATE_BUCKET: autopark-bucket-dev
    # TEST_TF_VAR_STATE_FILE: autopark-dev.tfstate
    # TEST_TF_STATELOCK_TABLE: autopark-tf-table-dev

    # TEST_SONAR_PROJECT_KEY: ren-autopark-aws-key
    # TEST_SONAR_PROJECT_NAME: ren-autopark-aws
    
    # Secretes:-
    # ENV_DB_USERNAME_LAMBDA
    # ENV_DB_PASSWORD_LAMBDA
    # ENV_ACCESS_KEY_ID_LAMBDA
    # ENV_SECRET_ACCESS_KEY_LAMBDA

name : GitHub_API_TEST
on:
  workflow_dispatch:


jobs:
    job1:
        name: Checking for Variables Values
        runs-on: ubuntu-latest
        steps:
            - name: Print Variables Values
              run: |
                echo "${{vars.TEST_REGION}},${{vars.TEST_AWS_ACCOUNT_NO}},${{vars.TEST_STATEMENT_ID}},${{vars.TEST_LAMBDA_START}},${{vars.TEST_LAMBDA_STOP}},${{vars.TEST_TF_STATE_BUCKET}}.${{vars.TEST_TF_VAR_STATE_FILE}}.${{vars.TEST_TF_STATELOCK_TABLE}}.${{vars.TEST_SONAR_PROJECT_KEY}}.${{vars.TEST_SONAR_PROJECT_NAME}}"
        
