
name : wf2 download
on:
  workflow_dispatch:
    # inputs:
    #   REGION_DEV:
    #     description: Region name for DEV ENV
    #     type: string
    #     required: true

# env:
  # REGION_DEV: ${{inputs.REGION_DEV}}
jobs:
# Configuring AWS.
    # AWS-configure:
    #     runs-on: ubuntu-latest
  
    #     steps:
    #       - name: Configure AWS Credentials(DEV ENV)
    #         uses: aws-actions/configure-aws-credentials@v4
    #         with:
    #           aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY }}
    #           aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #           aws-region: ${{ env.REGION_DEV }}
  download_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-name
          path: .
          ref: main  # Specify the branch name here

      - name: Read Name
        run: cat name.txt
