name: Workflow A
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Produce artifact
        id: artifact_step
        run: |
          echo "Hello, world" > hello.txt
      - name: Set artifact name as output
        run: echo "::set-output name=artifact_name::my-artifact"
        env:
          artifact_name: ${{ steps.artifact_step.outputs.artifact_name }}
      - name: Archive the artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.artifact_step.outputs.artifact_name }}
          path: hello.txt
