
name : GitHub_API_TEST
on:
  workflow_dispatch:
    inputs:
      REGION:
        description: Region name
        type: string
        required: true

env:
  REGION_DEV: ${{inputs.REGION}}
jobs:
# Configuring AWS.
    AWS-configure:
        runs-on: ubuntu-latest
  
        steps:
          - name: Configure AWS Credentials(DEV ENV)
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY }}
              aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ env.REGION_DEV }}
